server.port=8083
spring.application.name=pagamento-api
logging.file.name=../logs/pagamento-api.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n
logging.pattern.console=%d{HH:mm:ss.SSS} %-5level %logger{0} - %msg%n
logging.level.root=INFO